package tb

import (
	"github.com/alagunto/tb/telegram"
)

// SupportedCurrencies is an alias to telegram.SupportedCurrencies for backwards compatibility.
var SupportedCurrencies = telegram.SupportedCurrencies

// Deprecated: Use telegram.SupportedCurrencies directly
var _ = map[string]telegram.Currency{
	"AED": {Code: "AED", Title: "United Arab Emirates Dirham", Symbol: "AED", Native: "د.إ.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 367, MaxAmount: 3673200},
	"AFN": {Code: "AFN", Title: "Afghan Afghani", Symbol: "AFN", Native: "\u060b", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 7554, MaxAmount: 75540495},
	"ALL": {Code: "ALL", Title: "Albanian Lek", Symbol: "ALL", Native: "Lek", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: false, Exp: 2, MinAmount: 10908, MaxAmount: 109085036},
	"AMD": {Code: "AMD", Title: "Armenian Dram", Symbol: "AMD", Native: "դր.", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 48398, MaxAmount: 483984962},
	"ARS": {Code: "ARS", Title: "Argentine Peso", Symbol: "ARS", Native: "$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 3720, MaxAmount: 37202998},
	"AUD": {Code: "AUD", Title: "Australian Dollar", Symbol: "AU$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 139, MaxAmount: 1392750},
	"AZN": {Code: "AZN", Title: "Azerbaijani Manat", Symbol: "AZN", Native: "ман.", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 170, MaxAmount: 1702500},
	"BAM": {Code: "BAM", Title: "Bosnia & Herzegovina Convertible Mark", Symbol: "BAM", Native: "KM", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 171, MaxAmount: 1715550},
	"BDT": {Code: "BDT", Title: "Bangladeshi Taka", Symbol: "BDT", Native: "৳", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 8336, MaxAmount: 83367500},
	"BGN": {Code: "BGN", Title: "Bulgarian Lev", Symbol: "BGN", Native: "лв.", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 171, MaxAmount: 1716850},
	"BND": {Code: "BND", Title: "Brunei Dollar", Symbol: "BND", Native: "$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 134, MaxAmount: 1349850},
	"BOB": {Code: "BOB", Title: "Bolivian Boliviano", Symbol: "BOB", Native: "Bs", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 687, MaxAmount: 6877150},
	"BRL": {Code: "BRL", Title: "Brazilian Real", Symbol: "R$", Native: "R$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 377, MaxAmount: 3775397},
	"CAD": {Code: "CAD", Title: "Canadian Dollar", Symbol: "CA$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 132, MaxAmount: 1321950},
	"CHF": {Code: "CHF", Title: "Swiss Franc", Symbol: "CHF", Native: "CHF", ThousandsSep: "'", DecimalSep: ".", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 99, MaxAmount: 993220},
	"CLP": {Code: "CLP", Title: "Chilean Peso", Symbol: "CLP", Native: "$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 0, MinAmount: 666, MaxAmount: 6665199},
	"CNY": {Code: "CNY", Title: "Chinese Renminbi Yuan", Symbol: "CN¥", Native: "CN¥", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 674, MaxAmount: 6747298},
	"COP": {Code: "COP", Title: "Colombian Peso", Symbol: "COP", Native: "$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 315595, MaxAmount: 3155950000},
	"CRC": {Code: "CRC", Title: "Costa Rican Colón", Symbol: "CRC", Native: "₡", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 60113, MaxAmount: 601130282},
	"CZK": {Code: "CZK", Title: "Czech Koruna", Symbol: "CZK", Native: "Kč", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 2251, MaxAmount: 22510978},
	"DKK": {Code: "DKK", Title: "Danish Krone", Symbol: "DKK", Native: "kr", ThousandsSep: "", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 654, MaxAmount: 6545403},
	"DOP": {Code: "DOP", Title: "Dominican Peso", Symbol: "DOP", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 5032, MaxAmount: 50329504},
	"DZD": {Code: "DZD", Title: "Algerian Dinar", Symbol: "DZD", Native: "د.ج.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 11872, MaxAmount: 118729869},
	"EGP": {Code: "EGP", Title: "Egyptian Pound", Symbol: "EGP", Native: "ج.م.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 1791, MaxAmount: 17912012},
	"EUR": {Code: "EUR", Title: "Euro", Symbol: "€", Native: "€", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 87, MaxAmount: 877155},
	"GBP": {Code: "GBP", Title: "British Pound", Symbol: "£", Native: "£", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 75, MaxAmount: 757605},
	"GEL": {Code: "GEL", Title: "Georgian Lari", Symbol: "GEL", Native: "GEL", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 266, MaxAmount: 2663750},
	"GTQ": {Code: "GTQ", Title: "Guatemalan Quetzal", Symbol: "GTQ", Native: "Q", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 768, MaxAmount: 7689850},
	"HKD": {Code: "HKD", Title: "Hong Kong Dollar", Symbol: "HK$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 784, MaxAmount: 7845505},
	"HNL": {Code: "HNL", Title: "Honduran Lempira", Symbol: "HNL", Native: "L", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 2427, MaxAmount: 24277502},
	"HRK": {Code: "HRK", Title: "Croatian Kuna", Symbol: "HRK", Native: "kn", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 650, MaxAmount: 6506302},
	"HUF": {Code: "HUF", Title: "Hungarian Forint", Symbol: "HUF", Native: "Ft", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 27844, MaxAmount: 278440341},
	"IDR": {Code: "IDR", Title: "Indonesian Rupiah", Symbol: "IDR", Native: "Rp", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 1406555, MaxAmount: 14065550000},
	"ILS": {Code: "ILS", Title: "Israeli New Sheqel", Symbol: "₪", Native: "₪", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 366, MaxAmount: 3668230},
	"INR": {Code: "INR", Title: "Indian Rupee", Symbol: "₹", Native: "₹", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 7090, MaxAmount: 70900503},
	"ISK": {Code: "ISK", Title: "Icelandic Króna", Symbol: "ISK", Native: "kr", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 0, MinAmount: 119, MaxAmount: 1195599},
	"JMD": {Code: "JMD", Title: "Jamaican Dollar", Symbol: "JMD", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 13153, MaxAmount: 131539958},
	"JPY": {Code: "JPY", Title: "Japanese Yen", Symbol: "¥", Native: "￥", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 0, MinAmount: 109, MaxAmount: 1095549},
	"KES": {Code: "KES", Title: "Kenyan Shilling", Symbol: "KES", Native: "Ksh", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 10032, MaxAmount: 100322011},
	"KGS": {Code: "KGS", Title: "Kyrgyzstani Som", Symbol: "KGS", Native: "KGS", ThousandsSep: "\u00a0", DecimalSep: "-", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 6982, MaxAmount: 69820300},
	"KRW": {Code: "KRW", Title: "South Korean Won", Symbol: "₩", Native: "₩", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 0, MinAmount: 1119, MaxAmount: 11190001},
	"KZT": {Code: "KZT", Title: "Kazakhstani Tenge", Symbol: "KZT", Native: "₸", ThousandsSep: "\u00a0", DecimalSep: "-", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 37767, MaxAmount: 377674954},
	"LBP": {Code: "LBP", Title: "Lebanese Pound", Symbol: "LBP", Native: "ل.ل.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 150080, MaxAmount: 1500802255},
	"LKR": {Code: "LKR", Title: "Sri Lankan Rupee", Symbol: "LKR", Native: "රු.", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 18078, MaxAmount: 180789638},
	"MAD": {Code: "MAD", Title: "Moroccan Dirham", Symbol: "MAD", Native: "د.م.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 955, MaxAmount: 9554850},
	"MDL": {Code: "MDL", Title: "Moldovan Leu", Symbol: "MDL", Native: "MDL", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 1703, MaxAmount: 17038967},
	"MNT": {Code: "MNT", Title: "Mongolian Tögrög", Symbol: "MNT", Native: "MNT", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 261750, MaxAmount: 2617500000},
	"MUR": {Code: "MUR", Title: "Mauritian Rupee", Symbol: "MUR", Native: "MUR", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 3438, MaxAmount: 34384499},
	"MVR": {Code: "MVR", Title: "Maldivian Rufiyaa", Symbol: "MVR", Native: "MVR", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 1550, MaxAmount: 15501063},
	"MXN": {Code: "MXN", Title: "Mexican Peso", Symbol: "MX$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 1898, MaxAmount: 18988704},
	"MYR": {Code: "MYR", Title: "Malaysian Ringgit", Symbol: "MYR", Native: "RM", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 412, MaxAmount: 4124501},
	"MZN": {Code: "MZN", Title: "Mozambican Metical", Symbol: "MZN", Native: "MTn", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 6188, MaxAmount: 61889913},
	"NGN": {Code: "NGN", Title: "Nigerian Naira", Symbol: "NGN", Native: "₦", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 36174, MaxAmount: 361749532},
	"NIO": {Code: "NIO", Title: "Nicaraguan Córdoba", Symbol: "NIO", Native: "C$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 3241, MaxAmount: 32415503},
	"NOK": {Code: "NOK", Title: "Norwegian Krone", Symbol: "NOK", Native: "kr", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 851, MaxAmount: 8510100},
	"NPR": {Code: "NPR", Title: "Nepalese Rupee", Symbol: "NPR", Native: "नेरू", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 11299, MaxAmount: 112995016},
	"NZD": {Code: "NZD", Title: "New Zealand Dollar", Symbol: "NZ$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 146, MaxAmount: 1461850},
	"PAB": {Code: "PAB", Title: "Panamanian Balboa", Symbol: "PAB", Native: "B/.", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 99, MaxAmount: 995290},
	"PEN": {Code: "PEN", Title: "Peruvian Nuevo Sol", Symbol: "PEN", Native: "S/.", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 333, MaxAmount: 3331250},
	"PHP": {Code: "PHP", Title: "Philippine Peso", Symbol: "PHP", Native: "₱", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 5260, MaxAmount: 52602981},
	"PKR": {Code: "PKR", Title: "Pakistani Rupee", Symbol: "PKR", Native: "₨", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 13921, MaxAmount: 139214990},
	"PLN": {Code: "PLN", Title: "Polish Złoty", Symbol: "PLN", Native: "zł", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 376, MaxAmount: 3764026},
	"PYG": {Code: "PYG", Title: "Paraguayan Guaraní", Symbol: "PYG", Native: "₲", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 0, MinAmount: 6013, MaxAmount: 60134502},
	"QAR": {Code: "QAR", Title: "Qatari Riyal", Symbol: "QAR", Native: "ر.ق.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 364, MaxAmount: 3641101},
	"RON": {Code: "RON", Title: "Romanian Leu", Symbol: "RON", Native: "RON", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 417, MaxAmount: 4172003},
	"RSD": {Code: "RSD", Title: "Serbian Dinar", Symbol: "RSD", Native: "дин.", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 10391, MaxAmount: 103910127},
	"RUB": {Code: "RUB", Title: "Russian Ruble", Symbol: "RUB", Native: "руб.", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 6598, MaxAmount: 65986027},
	"SAR": {Code: "SAR", Title: "Saudi Riyal", Symbol: "SAR", Native: "ر.س.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 373, MaxAmount: 3732650},
	"SEK": {Code: "SEK", Title: "Swedish Krona", Symbol: "SEK", Native: "kr", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 904, MaxAmount: 9047896},
	"SGD": {Code: "SGD", Title: "Singapore Dollar", Symbol: "SGD", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 135, MaxAmount: 1353897},
	"THB": {Code: "THB", Title: "Thai Baht", Symbol: "฿", Native: "฿", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 3156, MaxAmount: 31563499},
	"TJS": {Code: "TJS", Title: "Tajikistani Somoni", Symbol: "TJS", Native: "TJS", ThousandsSep: "\u00a0", DecimalSep: ";", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 938, MaxAmount: 9389950},
	"TRY": {Code: "TRY", Title: "Turkish Lira", Symbol: "TRY", Native: "TL", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 526, MaxAmount: 5267200},
	"TTD": {Code: "TTD", Title: "Trinidad and Tobago Dollar", Symbol: "TTD", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 675, MaxAmount: 6757850},
	"TWD": {Code: "TWD", Title: "New Taiwan Dollar", Symbol: "NT$", Native: "NT$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 3072, MaxAmount: 30722993},
	"TZS": {Code: "TZS", Title: "Tanzanian Shilling", Symbol: "TZS", Native: "TSh", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 230200, MaxAmount: 2302000188},
	"UAH": {Code: "UAH", Title: "Ukrainian Hryvnia", Symbol: "UAH", Native: "₴", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: false, Exp: 2, MinAmount: 2764, MaxAmount: 27648991},
	"UGX": {Code: "UGX", Title: "Ugandan Shilling", Symbol: "UGX", Native: "USh", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 0, MinAmount: 3657, MaxAmount: 36575502},
	"USD": {Code: "USD", Title: "United States Dollar", Symbol: "$", Native: "$", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: false, Exp: 2, MinAmount: 100, MaxAmount: 1000000},
	"UYU": {Code: "UYU", Title: "Uruguayan Peso", Symbol: "UYU", Native: "$", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 3246, MaxAmount: 32469503},
	"UZS": {Code: "UZS", Title: "Uzbekistani Som", Symbol: "UZS", Native: "UZS", ThousandsSep: "\u00a0", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 2, MinAmount: 832759, MaxAmount: 8327599915},
	"VND": {Code: "VND", Title: "Vietnamese Đồng", Symbol: "₫", Native: "₫", ThousandsSep: ".", DecimalSep: ",", SymbolLeft: false, SpaceBetween: true, Exp: 0, MinAmount: 23084, MaxAmount: 230840500},
	"YER": {Code: "YER", Title: "Yemeni Rial", Symbol: "YER", Native: "ر.ي.\u200f", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 25030, MaxAmount: 250301249},
	"ZAR": {Code: "ZAR", Title: "South African Rand", Symbol: "ZAR", Native: "R", ThousandsSep: ",", DecimalSep: ".", SymbolLeft: true, SpaceBetween: true, Exp: 2, MinAmount: 1362, MaxAmount: 13620106},
}
