package react

import (
	"github.com/alagunto/tb/telegram"
)

func ReactionEmoji(emoji string) telegram.ReactionType {
	return telegram.ReactionType{Type: telegram.ReactionTypeEmoji, Emoji: emoji}
}

// Currently available emojis.
var (
	ThumbUp                   = ReactionEmoji("👍")
	ThumbDown                 = ReactionEmoji("👎")
	Heart                     = ReactionEmoji("❤")
	Fire                      = ReactionEmoji("🔥")
	HeartEyes                 = ReactionEmoji("😍")
	ClappingHands             = ReactionEmoji("👏")
	GrinningFace              = ReactionEmoji("😁")
	ThinkingFace              = ReactionEmoji("🤔")
	ExplodingHead             = ReactionEmoji("🤯")
	ScreamingFace             = ReactionEmoji("😱")
	SwearingFace              = ReactionEmoji("🤬")
	CryingFace                = ReactionEmoji("😢")
	PartyPopper               = ReactionEmoji("🎉")
	StarStruck                = ReactionEmoji("🤩")
	VomitingFace              = ReactionEmoji("🤮")
	PileOfPoo                 = ReactionEmoji("💩")
	PrayingHands              = ReactionEmoji("🙏")
	OkHand                    = ReactionEmoji("👌")
	DoveOfPeace               = ReactionEmoji("🕊")
	ClownFace                 = ReactionEmoji("🤡")
	YawningFace               = ReactionEmoji("🥱")
	WoozyFace                 = ReactionEmoji("🥴")
	Whale                     = ReactionEmoji("🐳")
	HeartOnFire               = ReactionEmoji("❤‍🔥")
	MoonFace                  = ReactionEmoji("🌚")
	HotDog                    = ReactionEmoji("🌭")
	HundredPoints             = ReactionEmoji("💯")
	RollingOnTheFloorLaughing = ReactionEmoji("🤣")
	Lightning                 = ReactionEmoji("⚡")
	Banana                    = ReactionEmoji("🍌")
	Trophy                    = ReactionEmoji("🏆")
	BrokenHeart               = ReactionEmoji("💔")
	FaceWithRaisedEyebrow     = ReactionEmoji("🤨")
	NeutralFace               = ReactionEmoji("😐")
	Strawberry                = ReactionEmoji("🍓")
	Champagne                 = ReactionEmoji("🍾")
	KissMark                  = ReactionEmoji("💋")
	MiddleFinger              = ReactionEmoji("🖕")
	EvilFace                  = ReactionEmoji("😈")
	SleepingFace              = ReactionEmoji("😴")
	LoudlyCryingFace          = ReactionEmoji("😭")
	NerdFace                  = ReactionEmoji("🤓")
	Ghost                     = ReactionEmoji("👻")
	Engineer                  = ReactionEmoji("👨‍💻")
	Eyes                      = ReactionEmoji("👀")
	JackOLantern              = ReactionEmoji("🎃")
	NoMonkey                  = ReactionEmoji("🙈")
	SmilingFaceWithHalo       = ReactionEmoji("😇")
	FearfulFace               = ReactionEmoji("😨")
	Handshake                 = ReactionEmoji("🤝")
	WritingHand               = ReactionEmoji("✍")
	HuggingFace               = ReactionEmoji("🤗")
	Brain                     = ReactionEmoji("🫡")
	SantaClaus                = ReactionEmoji("🎅")
	ChristmasTree             = ReactionEmoji("🎄")
	Snowman                   = ReactionEmoji("☃")
	NailPolish                = ReactionEmoji("💅")
	ZanyFace                  = ReactionEmoji("🤪")
	Moai                      = ReactionEmoji("🗿")
	Cool                      = ReactionEmoji("🆒")
	HeartWithArrow            = ReactionEmoji("💘")
	HearMonkey                = ReactionEmoji("🙉")
	Unicorn                   = ReactionEmoji("🦄")
	FaceBlowingKiss           = ReactionEmoji("😘")
	Pill                      = ReactionEmoji("💊")
	SpeaklessMonkey           = ReactionEmoji("🙊")
	Sunglasses                = ReactionEmoji("😎")
	AlienMonster              = ReactionEmoji("👾")
	ManShrugging              = ReactionEmoji("🤷‍♂️")
	PersonShrugging           = ReactionEmoji("🤷")
	WomanShrugging            = ReactionEmoji("🤷‍♀️")
	PoutingFace               = ReactionEmoji("😡")
)
